create table attendance
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    presence boolean,
    lesson_id int8,
    primary key (id));

create table department
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    department_name varchar(255) not null,
    faculty_id int8,
    primary key (id));

create table direction
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    direction_code varchar(255) not null,
    direction_name varchar(255) not null,
    faculty_id int8,
    primary key (id));

create table faculty
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    faculty_name varchar(255) not null,
    university_name int8,
    primary key (id));

create table homework
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    file bytea not null,
    file_type varchar(255) not null,
    note varchar(255),
    lesson_id int8,
    primary key (id));

create table job_ad
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    category varchar(255) not null,
    description varchar(255) not null,
    job_name varchar(255) not null,
    link varchar(255) not null,
    faculty_id int8,
    primary key (id));

create table lesson
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    date timestamp not null,
    lesson_unit_id int8,
    group_id int8,
    primary key (id));

create table lesson_unit
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    audience varchar(255) not null,
    end_time time not null,
    note varchar(255),
    start_time time not null,
    type varchar(255) not null,
    subject_id int8,
    teacher_id int8,
    primary key (id));

create table library
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    university_name int8,
    primary key (id));

create table mark
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    mark_value varchar(255) not null,
    lesson_id int8,
    student_id int8,
    primary key (id));

create table material
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    link varchar(255) not null,
    library_id int8,
    subject_id int8,
    primary key (id));

create table student
(
    id int8 not null,
    created_by varchar(255),
    modified_by varchar(255),
    department_id int8 not null,
    direction_id int8,
    group_id int8 not null,
    primary key (id));

create table student_council
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    audience varchar(255) not null,
    email varchar(255) not null,
    phone varchar(255) not null,
    vk_team varchar(255) not null,
    faculty_id int8,
    primary key (id));

create table subject
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    subject_name varchar(255) not null,
    team_id int8,
    primary key (id));

create table teacher
(
    id int8 not null,
    created_by varchar(255),
    modified_by varchar(255),
    personal_page varchar(255) not null,
    department_id int8 not null,
    direction_id int8,
    primary key (id));

create table teachers_feedback
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    content varchar(255) not null,
    header varchar(255) not null,
    author_id int8,
    teacher_id int8,
    primary key (id));

create table team
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    course int4 not null,
    team_name int4 not null,
    direction_id int8,
    primary key (id));

create table university
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    university_name varchar(255),
    primary key (id));

create table usr
(
    id int8 generated by default as identity,
    created_by varchar(255),
    modified_by varchar(255),
    email varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    patronymic varchar(255) not null,
    phone varchar(255) not null,
    primary key (id));

alter table if exists attendance
    add constraint attendance_fk
        foreign key (lesson_id) references lesson;

alter table if exists department
    add constraint department_fk
        foreign key (faculty_id) references faculty;

alter table if exists direction
    add constraint direction_fk
        foreign key (faculty_id) references faculty;

alter table if exists faculty
    add constraint faculty_fk
        foreign key (university_name) references university;

alter table if exists homework
    add constraint homework_fk
        foreign key (lesson_id) references lesson;

alter table if exists job_ad
    add constraint job_ad_fk
        foreign key (faculty_id) references faculty;

alter table if exists lesson
    add constraint lesson_to_lesson_unit_fk
        foreign key (lesson_unit_id) references lesson_unit;

alter table if exists lesson
    add constraint lesson_to_team_fk
        foreign key (group_id) references team;

alter table if exists lesson_unit
    add constraint lesson_unit_to_subject_fk
        foreign key (subject_id) references subject;

alter table if exists lesson_unit
    add constraint lesson_unit_to_teacher_fk
        foreign key (teacher_id) references teacher;

alter table if exists library
    add constraint library_fk
        foreign key (university_name) references university;

alter table if exists mark
    add constraint mark_to_lesson_fk
        foreign key (lesson_id) references lesson;

alter table if exists mark
    add constraint mark_to_student_fk
        foreign key (student_id) references student;

alter table if exists material
    add constraint material_to_library_fk
        foreign key (library_id) references library;

alter table if exists material
    add constraint material_to_subject_fk
        foreign key (subject_id) references subject;

alter table if exists student
    add constraint student_to_department_fk
        foreign key (department_id) references department;

alter table if exists student
    add constraint student_to_direction_fk
        foreign key (direction_id) references direction;

alter table if exists student
    add constraint student_to_team_fk
        foreign key (group_id) references team;

alter table if exists student
    add constraint student_to_usr_fk
        foreign key (id) references usr;

alter table if exists student_council
    add constraint student_council_fk
        foreign key (faculty_id) references faculty;

alter table if exists subject
    add constraint subject_fk
        foreign key (team_id) references team;

alter table if exists teacher
    add constraint teacher_to_department_fk
        foreign key (department_id) references department;

alter table if exists teacher
    add constraint teacher_to_direction_fk
        foreign key (direction_id) references direction;

alter table if exists teacher
    add constraint teacher_to_usr_fk
        foreign key (id) references usr;

alter table if exists teachers_feedback
    add constraint teachers_feedback_to_usr_fk
        foreign key (author_id) references usr;

alter table if exists teachers_feedback
    add constraint teachers_feedback_to_teacher_fk
        foreign key (teacher_id) references teacher;

alter table if exists team
    add constraint team_fk
        foreign key (direction_id) references direction;